name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dio: ^5.5.0+1
  fhir_rest_client:
    path: ../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
